@startuml context-core
!theme plain
top to bottom direction

state start <<start>>
state end <<end>>
state openCondition <<choice>>
state finishGameCondition <<choice>>
state saveCondition <<choice>>
state INITIAL
state IN_GAME
state RESUME

start --> INITIAL
INITIAL --> IN_GAME :Start
INITIAL --> openCondition :Open
openCondition --> IN_GAME
openCondition --> saveCondition :[isFinished]
IN_GAME --> finishGameCondition :ProposeComb.
IN_GAME --> IN_GAME :Undo\nRedo
IN_GAME --> saveCondition :Exit
finishGameCondition --> IN_GAME
finishGameCondition --> saveCondition :[isFinished]
saveCondition --> RESUME :Save
saveCondition --> RESUME 
RESUME --> end 
RESUME --> INITIAL :Resume

@enduml