@startuml analysis-architecture
!theme plain

package analysis{
    boundary XView
    control XController
    entity XDAO
    entity XModel
}


XView ..> XController
XView ..> XModel
XController ..> XModel
XController ..> XDAO

package front <<Text Console>> {
    boundary XConsoleView
    boundary XConsole
    boundary XMessage
}

XConsoleView .up.> XView
XConsoleView .up.> XController
XConsoleView --> XConsole
XConsoleView --> XMessage
XConsoleView ..> XModel
XConsole .up.> XView
XMessage .up.> XView
XMessage --> XConsole

package backend <<FileWriter>> {
    entity XSessionImpDAO
    entity XGameDAO
}

XSessionImpDAO .up.> XDAO
XSessionImpDAO .up.> XModel
XSessionImpDAO --> XGameDAO
XGameDAO .up.> XModel

package app-core <<Maven dependency>> {
    entity CoreSessionDAO <<abstract>>
    boundary CoreViews <<abstract>>
    control CoreControllers
    entity CoreModels
}

CoreControllers --> CoreModels
CoreControllers --> CoreSessionDAO
CoreViews --> CoreControllers

front .left.> CoreControllers
front .down.> CoreViews
front .down.> CoreModels
backend ..> CoreSessionDAO
backend ..> CoreModels

@enduml